title: Welcome to my website!
logo: /assets/img/logo.png
description: This is my personal website, where you can find  all the information about my professional background
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
